set -g default-shell /bin/zsh
set -g mouse on
set -g history-limit 5000

set -g status-style bg=#1e1e2e,fg=#cdd6f4
set -g pane-border-style fg=#45475a
set -g pane-active-border-style fg=#89b4fa
set -g status-left "#[bg=#89b4fa,fg=#1e1e2e] #H #[bg=default,fg=default] "
set -g status-left-length 60