export EDITOR=vi
export VISUAL=vi

if [ -f /root/.nix-profile/bin/starship ]; then
  eval "$(starship init zsh)"
fi

if [ -f /root/.nix-profile/bin/zoxide ]; then
  eval "$(zoxide init zsh)"
fi

alias ls='eza'
alias ll='eza -l --git'
alias la='eza -la --git'
alias cat='bat --paging=never'
alias grep='rg'
alias cd='z'