apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    backstage.io/kubernetes-id: ${{ values.name }}
    backstage.io/techdocs-ref: dir:.
  tags:
    - nix
    - sandbox
  links:
    - url: https://${{ values.name }}-terminal.${{ values.terminalHost }}:8443
      title: Terminal
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}