#!/usr/bin/env bash
# scripts/mirror-platform-repos.sh — 3-way mirror sync for platform-generated repos
#
# Syncs the 6 idpbuilder-localdev-* repos Gitea → local → GitHub:
#   [1] Local clones live in mirrors/ (pull-only, never published to Gitea)
#   [2] Gitea org repos are downstream (generated by idpbuilder create)
#   [3] GitHub org repos are the durable backup (survive unimart close)
#
# Pull-only: content flows from Gitea (fresh idpbuilder output) to GitHub —
# never the other way, and mirror clones are never pushed into Gitea.
#
# Usage:
#   scripts/mirror-platform-repos.sh           # sync all 6 repos
#   scripts/mirror-platform-repos.sh --dry-run # report drift without changing
#
# Requires: running cluster and write access to github.com (gh or ssh key).
# Auto-wired into `unimart open` and `unimart reload`.

set -euo pipefail

# ── Colors ────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

info() { printf "${CYAN}[info]${RESET}  %s\n" "$*"; }
ok() { printf "${GREEN}[ok]${RESET}    %s\n" "$*"; }
warn() { printf "${YELLOW}[warn]${RESET}  %s\n" "$*"; }
fail() {
	printf "${RED}[fail]${RESET}  %s\n" "$*" >&2
	exit 1
}

# ── Resolve paths ─────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
LOCAL_DIR="${REPO_ROOT}/mirrors"

ORG="Unimart-For-Operations"
GITEA_URL="${GITEA_URL:-https://gitea.cnoe.localtest.me:8443}"
GIT_FLAGS=(-c http.sslVerify=false)
REPOS=(
	"idpbuilder-localdev-gitea"
	"idpbuilder-localdev-nginx"
	"idpbuilder-localdev-argocd"
	"idpbuilder-localdev-act-runner-act-runner"
	"idpbuilder-localdev-backstage-backstage"
	"idpbuilder-localdev-nix-sandboxes-nix-sandboxes"
)

DRY_RUN=false
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=true

# ── Credentials ──────────────────────────────────────────────────────────
GITEA_USER="$(kubectl get secret -n gitea gitea-credential -o jsonpath='{.data.username}' 2>/dev/null | base64 -d)" \
	|| warn "could not read gitea-credential secret — is the cluster running?"
GITEA_PASS="$(kubectl get secret -n gitea gitea-credential -o jsonpath='{.data.password}' 2>/dev/null | base64 -d)" \
	|| warn "could not read gitea-credential secret — is the cluster running?"
AUTH_URL="${GITEA_URL#https://}"
AUTH_URL="https://${GITEA_USER}:${GITEA_PASS}@${AUTH_URL}"

if ! curl -sk --max-time 5 "${GITEA_URL}/api/v1/version" >/dev/null; then
	warn "Gitea not reachable at ${GITEA_URL}"
	fail "missing running cluster / Gitea endpoint"
fi
ok "Gitea reachable at ${GITEA_URL}"

for repo in "${REPOS[@]}"; do
	echo ""
	info "━━ ${repo} ━━"
	local_dir="${LOCAL_DIR}/${repo}"

	gitea_ref="$(git "${GIT_FLAGS[@]}" ls-remote "${AUTH_URL}/${ORG}/${repo}.git" HEAD 2>/dev/null | awk '{print $1}')"
	git_hub_ref="$(git ls-remote "git@github.com:${ORG}/${repo}.git" HEAD 2>/dev/null | awk '{print $1}')"
	[[ -d "${local_dir}/.git" ]] && local_ref="$(git -C "${local_dir}" rev-parse HEAD)" || local_ref="(missing)"

	info "local:  ${local_ref:-unknown}"
	info "gitea:  ${gitea_ref:-unknown}"
	info "github: ${git_hub_ref:-unknown}"

	if [[ -z "${gitea_ref}" ]]; then
		warn "no gitea ref for ${repo} — skipping"
		continue
	fi

	if [[ "${gitea_ref}" == "${git_hub_ref}" && "${gitea_ref}" == "${local_ref}" ]]; then
		ok "in sync (${gitea_ref:0:8})"
		continue
	fi

	if [[ "${DRY_RUN}" == "true" ]]; then
		warn "drift detected — would sync to gitea ref ${gitea_ref:0:8}"
		continue
	fi

	# Reset local clone to the gitea ref, then propagate to GitHub (primary backup).
	if [[ -d "${local_dir}/.git" ]]; then
		git "${GIT_FLAGS[@]}" -C "${local_dir}" fetch --prune "${AUTH_URL}/${ORG}/${repo}.git" main
		git -C "${local_dir}" checkout -q -B main FETCH_HEAD
		git -C "${local_dir}" push -q origin main
	else
		mkdir -p "${LOCAL_DIR}"
		git "${GIT_FLAGS[@]}" clone "${AUTH_URL}/${ORG}/${repo}.git" "${local_dir}"
		git -C "${local_dir}" remote add origin "git@github.com:${ORG}/${repo}.git"
		git -C "${local_dir}" push -q origin main
	fi
	ok "synced local + github to gitea ref ${gitea_ref:0:8}"

	if [[ -z "${git_hub_ref}" ]]; then
		warn "github repo missing — create with: gh repo create ${ORG}/${repo} --public"
	fi
done

echo ""
ok "mirror sync complete"