apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-sandbox
  description: Example Nix sandbox provisioned by the nix-sandbox scaffolder template
  annotations:
    backstage.io/kubernetes-id: example-sandbox
    backstage.io/techdocs-ref: dir:.
  tags:
    - nix
    - sandbox
  links:
    - url: https://example-sandbox-terminal.cnoe.localtest.me
      title: Terminal
spec:
  type: service
  lifecycle: experimental
  owner: platform-team