apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  destination:
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  source:
    repoURL: cnoe://kube-prometheus-stack
    targetRevision: HEAD
    path: "."
    helm:
      valueFiles:
        - local-values.yaml
      includeCrds: true
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m